### ISSUE TITLE
MAINT: drop the direct rand dependency for getrandom — one 32-byte OS fill does not need the rand tree

### ISSUE THREAD

**Issue by deffenda** [ABD-Enterprises/terminal-workspace#314]
## Problem

Dependabot #307 bumps `rand` 0.8 → 0.10 in `src-tauri`, and it **cannot merge**: `rand` 0.10
renamed `OsRng` to `SysRng` and replaced `RngCore` with a fallible `TryRng`, so CI fails with

```
error[E0432]: unresolved imports `rand::rngs::OsRng`, `rand::RngCore`
  --> src/main.rs:21
```

## The better fix than migrating the API

`rand` has exactly **one** direct use in this tree — filling the 32-byte per-process salt
introduced by #302 for the ssh-config cycle key:

```rust
let mut salt = [0_u8; 32];
OsRng.fill_bytes(&mut salt);
```

Pulling the whole `rand` tree for one OS-entropy fill is more dependency than the job needs, and
every future `rand` major becomes another blocked bump. Depending on `getrandom` directly is
smaller and more precise, and it is what `rand`'s OS source wraps anyway.

The security property from #302 must survive unchanged: **256 bits of OS randomness generated
once at process start** — never a PID, timestamp, or constant, because a digest under a
derivable salt turns cycle keys into a path-existence oracle. The replacement must also **fail
closed** rather than proceeding with a zero salt.

Note `rand` 0.8 remains in `Cargo.lock` transitively for other crates; this removes only the
direct dependency.

## Supersedes

Closes Dependabot #307 — the bump it proposes is unnecessary once the direct dependency is gone.

```ai-task
{
  "scope": [
    "src-tauri/Cargo.toml",
    "src-tauri/Cargo.lock",
    "src-tauri/src/main.rs"
  ],
  "depends_on": [],
  "done_when": [
    "src-tauri has no direct rand dependency",
    "the cycle-key salt is still 32 bytes of OS entropy obtained once at process start, and the call fails closed rather than yielding a zero salt",
    "cargo build and cargo test pass for src-tauri",
    "bash scripts/native-audit.sh passes",
    "bash scripts/validate.sh exits 0"
  ],
  "validation": {
    "local": [
      "bash scripts/validate.sh"
    ],
    "review": []
  },
  "checks": [
    {"type": "absent", "path": "src-tauri/Cargo.toml", "pattern": "rand = ", "for": 1},
    {"type": "grep", "path": "src-tauri/Cargo.toml", "pattern": "getrandom", "for": 1},
    {"type": "absent", "path": "src-tauri/src/main.rs", "pattern": "OsRng", "for": 2},
    {"type": "grep", "path": "src-tauri/src/main.rs", "pattern": "fill\\(&mut salt\\)", "for": 2}
  ],
  "review_points": [
    "Do not substitute a seeded or userspace PRNG. The salt must come from the OS.",
    "Fail closed on an entropy error — a zero salt would silently defeat the oracle protection #302 added."
  ]
}
```

Filed while draining the blocked Dependabot queue; the API break is what made #307 unmergeable.

**Comment by deffenda** [comment]
### ai-evidence

- type: run-presence
- status: passed
- ref: finish-pr (hand-authored); run_id=orc-run-20260821113531209-81e53718-1640-4672-9c02-24481c08beb6
- commit: 5dd7f58a67e97b601f73625d9531a8b3e7416927
- recorded_at: 2026-08-21T11:35:35.231Z
